awk 'NR!=1&&$1!=t{print >"final_ws_55.dat"}{t=$1}' final_working_set.dat-55
awk 'NR!=1&&$1!=t{print >"final_ws_60.dat"}{t=$1}' final_working_set.dat-60
awk 'NR!=1&&$1!=t{print >"final_ws_65.dat"}{t=$1}' final_working_set.dat-65
awk 'NR!=1&&$1!=t{print >"final_ws_70.dat"}{t=$1}' final_working_set.dat-70
awk 'NR!=1&&$1!=t{print >"final_ws_75.dat"}{t=$1}' final_working_set.dat-75
awk 'NR!=1&&$1!=t{print >"final_ws_80.dat"}{t=$1}' final_working_set.dat-80
awk 'NR!=1&&$1!=t{print >"final_ws_85.dat"}{t=$1}' final_working_set.dat-85
awk 'NR!=1&&$1!=t{print >"final_ws_90.dat"}{t=$1}' final_working_set.dat-90
awk 'NR!=1&&$1!=t{print >"final_ws_95.dat"}{t=$1}' final_working_set.dat-95